[default]
host = "..us-east-1.rds.amazonaws.com"
port = "3306"
database = "cindidevops"
user = "root"
password = ""
charset = "utf8"
sql_log = true

MaxIdleConns = 10 #空闲时最大的连接数
MaxOpenConns = 100 #最大的连接数
